language: java
jdk:
  - oraclejdk8

branches:
  only:
  - master

script:
  - mvn clean test

after_success:
  - mvn clean -DrepoToken=$repoToken cobertura:cobertura coveralls:report
  - VERSION=$( grep -oPm1 "(?<=<version>)[^-SNAPSHOT<]+" pom.xml | head -1)
  - TAG="mysql-binlog-replicator-$VERSION"
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - git checkout master
  - mvn -s ./.travis.settings.xml  --batch-mode -Dtag=$TAG -DreleaseVersion=$VERSION -Dgh.token=$GH_TOKEN -Dgpg.passphrase=$GPG_PASSPHRASE release:clean release:prepare
  - mvn -s ./.travis.settings.xml release:perform -Dgpg.passphrase=$GPG_PASSPHRASE -Dgh.token=$GH_TOKEN
  - git remote set-url origin https://$GH_TOKEN@github.com/juanwolf/mysql-binlog-replicator.git
  - git checkout -b develop
  - git commit pom.xml -m "feat(mvn): Changing project version [Travis]"
  - git push origin develop

env:
  global:
  - secure: GkGCYFr7Zf6sKdIySqBLm5HpvsZO9934S4TlArdlfqO+kiMqNCKOcB2qN01daiFFxhPocxaMkCi6Wgxry0N8oaT1x1RS2e7lt69H7fZSYUEQoxDPLEKE+jQKPumq6XR/z9m5NltkidRiOtnq4u8pl23y5+p8OAMk9KMp2MAsRYcnfLQ/nbEsFyF/3XH41CfErCIQ+mgVAVT3ZTOswsfzU1Cc0V9XQ0XuTk3uI8FailJKBSLy3L0pv7LWSSBLl7S4jlJDgO3B6628OXzGgxqaKqngLU7RaezB8lLxp9zdR1ydSEs83vLpJK9S0V5X5h6gVlyjYNrmuijG42lervQaH3+hCrdhZlIMzEo5oJUcqD6ZHupVu9pZQgd03Ce/IPU9bAKWF2YroiFyR8+ghcnmXY5R6Ci7Gr1qQKOtOsThoZXO0I5LRQfDHlC30L/7PSWLIVvhb1pyRWHkYOnQ4WPrW9IGjkFI89ihnoCdxO3Z212oYPi9vcfU5go7nwWumjcE7q3n1D1K0xdWNPtttIHRvPawj3KKM/nIxfEMjuvF/1A74OMfDQWWSpYamrBgUgMWCK7VJd07YOWidC3dhWE5xGhrrdaqBzJveCRxHt2Cyv16P+g/ulu+7qZdOg3refCFtY/Ixq67mT7kw7rutU65fGhvuy8IPGnRiInXxyTF4bc=
  - secure: NommQkVC/2c42NN36slMwyceV7AvZLnd9AJ9Rzdu4C1epo0B0M8Z9t+Pz2Y1vE01baqldp9HWXZ7U4YANz3cJNNjP9xjweifdF0AAB44JIFf0wOmOuCcxEc8J57RKroxIxbr2BbxcqeMFzWDlRh48wkJw0RLrLPbD6cz4oHER875mn5oN4I6tyqVJC8g/HQzHTYdDCDOv9Hsej/hPj9Hzm9EKKejL32ZgRXDHPwzVMB0KAfSFwU8wkI2tS8bOrJDlzdueHeF+pdP7IRrvO6FxdjoznKTVDqzT48p1jAPC5UY3awqwaFjKDZ0QQQXteASG44/pr/xWsvjxRGJtqVITZ6eeJ/Dq4xHew6WIobDScNsZqHENXEVx9DKj2ltj87VllCKyyrzO8mG7AzsKoIfpOavhlRnU5frwzZFftS56tbllmhj4rXBj++1VF3JnCJjXUYz3KlGcfUWIjbCINe/qPcp4btGwbSy8+6EOQQvGtfqfgajlR3fLvtRGVhYKXyIsXBkziel2T1YMv4S2ovcy7KDbCXkja/Ki9yA+4SHdLOqQaZ1Ax0DGyBLu8MFO0ohm3ffXQ80j/Pq4SYiaxr90fok2wVWzUl9yGoa2lXsfdTdhaJkL3FTnQBOAFsNztHD3tBBI2dxolVduaLcYRJ6zkjeCFPu0xU2DYNaIqmk2Ro=
  - secure: EjGEwrbSrjfntUSLUp7yOFlmEv8cOc+PIorcn8ILOV19XyZH7ixhM0WQD72xeaPj+VncDgDUIqgW2B1ERyOvfxLzY7klstK8seFemnCdcUe3yGORQ1ApjlgACFiIXxMHFrXVz59kSCLCh503+5CfduwnbUgWv266FwU/m/M6FgQ2NNxd2t7788bJo4oku+k2gNnbLxT3wW92aElRp/Q1ReutCvlqqqg+yxRf9Fl9t0u/aMBimOGiWW94rbOKP42jkJTY/MQ70SNBBW9UzTmi13QTOYILAW3yDhI2URC1QrXHlR1ZwoKgRH2MiLj4/BsLGWAXsWAwSmJ5dfDzdSaFrrNA88GpF6oB3TIKFdjq+yjgVtH/5rBLEpkPArahjYfHCmTh7YeiD4TyOuz0zCHydSAebss9NX6ieIaUCT1G4bbFujH7F8Lfc4yNT4tZhnCvlwSQx0tDZ6m4K4rdEuHubkw1WoDQgk7SXg4ZmiHbXhDBIlxvteS46k44reLt34zz3LRQlNmP7+eS9EsAUK+c6yAlGL46oFfUbH8DIKWjL12/fezrcqwMV3EkWbSC0UygUIK7uaG0RwYhv8rVu/VE1C6mcit4DMxX9kGSE8AC8bZ/i1Oy90k+j06y0gQAi+nhMiEb8AYYlktTc8YPkBqRTUdopRVCSGtSig1iQUnntT8=q
  - secure: P78g0LDfcOpproY9KGnJDsAB5H5EpZVoM+GNIx+NJlrKIuDQhaVJbhGuHFzMJDJg2PXEf/rKYv1wU8C4wZs9/N3AFi6cyknqt70rzAN2EVld+fcIr2iMg1TUeUY2zVCyPLVMpj/tjPGXOXS13EPFYwvhJnyCPNOnTTcWAff6WGEFf57IvwEGtOJ7+vumRqB346YPdoYXwAbmpU1spQSNVvne4qSg49VVZzes3KtGID0m7yRbS+o44DpbyO9K8/2FRae2fA3uySnjsRo2u0T8EotbxA86bsNM1pMN5m5Uo3Q3y2IdScfG2NBgsrl8j/+RrOgfocBviadDRUYNupLH6++yP0a6OcZ5JNH1j0+E7GeHlCNezUzUFQea7V4pj94BnRl61GeczeVoYm5wFRwqvb4/c1mjNpL/kkUffX3aV0HybbC2Rvh+pMATAoL8jti01kDmxM9M3KwCZMoznHAp4ktOmvENKvTmvdqmC44OROWb6TCXTAoOLgRmmNjuG2RIf2GXv3jnKYRbWQeWKlIWAGo7HSOwQm9067ZWR8qgfenVGQygjxclO4MoNEDZZY97tkAkuVdkYY7wS9i1os8fWLNKoWhsexH9wMnsNrIHdXKAY7Iovo/rqFSaPdEarsFo6+5XyEA3B+Gruvqk1IglGoz1q5LxB55rzwOm6Ct8vQ0=
